discount: 0.99
rewards:
  '[0, 0]': -1
  '[0, 10]': 1
  '[0, 13]': -1
  '[0, 5]': 1
  '[1, 0]': 1
  '[1, 10]': -1
  '[10, 0]': -1
  '[10, 11]': 1
  '[10, 3]': 1
  '[10, 8]': -1
  '[11, 11]': 1
  '[11, 13]': 1
  '[11, 2]': -1
  '[11, 4]': 1
  '[11, 5]': -1
  '[11, 9]': -1
  '[12, 0]': -1
  '[12, 10]': -1
  '[12, 13]': -1
  '[12, 1]': 1
  '[12, 3]': 1
  '[13, 14]': -1
  '[13, 3]': -1
  '[14, 10]': 1
  '[14, 14]': -1
  '[14, 1]': 1
  '[14, 2]': 1
  '[14, 5]': 1
  '[14, 7]': 1
  '[2, 0]': -1
  '[2, 10]': -1
  '[2, 13]': 1
  '[2, 1]': -1
  '[2, 5]': 1
  '[2, 7]': -1
  '[2, 9]': -1
  '[3, 13]': 1
  '[3, 4]': -1
  '[3, 8]': 1
  '[4, 0]': 1
  '[4, 10]': -1
  '[4, 11]': -1
  '[4, 12]': 1
  '[5, 0]': 1
  '[5, 11]': 1
  '[5, 2]': 1
  '[5, 5]': 1
  '[5, 6]': -1
  '[5, 7]': -1
  '[6, 11]': -1
  '[6, 13]': -1
  '[6, 14]': 1
  '[6, 9]': 1
  '[7, 0]': 1
  '[7, 10]': -1
  '[7, 13]': -1
  '[7, 14]': 1
  '[7, 2]': 1
  '[7, 4]': -1
  '[7, 9]': 1
  '[8, 10]': -1
  '[8, 11]': -1
  '[8, 1]': 1
  '[8, 2]': -1
  '[8, 4]': -1
  '[8, 5]': 1
  '[8, 6]': -1
  '[8, 8]': 1
  '[8, 9]': -1
  '[9, 10]': 1
  '[9, 1]': 1
  '[9, 4]': 1
  '[9, 5]': 1
  '[9, 6]': -1
  '[9, 8]': 1
size:
- 15
- 15
terminal_states: []
transition_prob: 0.8
walls:
- - 12
  - 5
- - 4
  - 11
- - 0
  - 0
- - 8
  - 9
- - 1
  - 12
- - 7
  - 9
- - 7
  - 10
- - 6
  - 1
- - 8
  - 0
- - 3
  - 9
- - 8
  - 8
- - 2
  - 13
- - 5
  - 0
- - 3
  - 11
white_reward: -0.04
