discount: 0.99
rewards:
  '[0, 11]': -1
  '[0, 12]': -1
  '[0, 4]': -1
  '[0, 6]': 1
  '[1, 12]': 1
  '[1, 3]': 1
  '[1, 5]': 1
  '[1, 6]': -1
  '[1, 8]': -1
  '[10, 0]': 1
  '[10, 10]': -1
  '[10, 11]': -1
  '[10, 1]': -1
  '[10, 2]': -1
  '[10, 4]': 1
  '[11, 11]': 1
  '[11, 1]': 1
  '[11, 9]': -1
  '[12, 5]': 1
  '[12, 7]': 1
  '[2, 4]': 1
  '[2, 6]': -1
  '[2, 8]': 1
  '[3, 0]': 1
  '[3, 10]': 1
  '[3, 12]': 1
  '[3, 2]': 1
  '[3, 7]': -1
  '[3, 8]': 1
  '[4, 11]': 1
  '[4, 4]': 1
  '[4, 5]': 1
  '[4, 8]': 1
  '[5, 11]': -1
  '[5, 12]': 1
  '[5, 2]': -1
  '[5, 4]': 1
  '[5, 5]': -1
  '[5, 7]': -1
  '[6, 12]': 1
  '[6, 1]': 1
  '[6, 5]': 1
  '[6, 8]': 1
  '[6, 9]': 1
  '[7, 0]': -1
  '[7, 10]': 1
  '[7, 11]': 1
  '[7, 3]': -1
  '[7, 4]': -1
  '[7, 6]': 1
  '[8, 0]': -1
  '[8, 2]': 1
  '[9, 11]': -1
  '[9, 2]': -1
  '[9, 6]': 1
  '[9, 8]': -1
size:
- 13
- 13
terminal_states: []
transition_prob: 0.8
walls:
- - 12
  - 4
- - 11
  - 4
- - 3
  - 5
- - 11
  - 11
- - 9
  - 6
- - 12
  - 9
- - 3
  - 10
- - 2
  - 6
- - 4
  - 5
- - 3
  - 2
- - 7
  - 8
- - 9
  - 4
white_reward: -0.04
