discount: 0.99
rewards:
  '[0, 10]': -1
  '[0, 11]': 1
  '[0, 12]': -1
  '[0, 13]': 1
  '[0, 14]': -1
  '[0, 15]': -1
  '[0, 16]': 1
  '[0, 6]': 1
  '[0, 9]': 1
  '[1, 12]': -1
  '[1, 13]': 1
  '[1, 14]': -1
  '[1, 2]': -1
  '[1, 4]': 1
  '[1, 5]': 1
  '[1, 9]': -1
  '[10, 14]': -1
  '[10, 15]': -1
  '[10, 3]': 1
  '[10, 8]': -1
  '[11, 0]': -1
  '[11, 12]': 1
  '[11, 3]': -1
  '[11, 5]': 1
  '[11, 8]': -1
  '[12, 0]': 1
  '[12, 12]': -1
  '[12, 14]': -1
  '[12, 1]': -1
  '[12, 9]': 1
  '[13, 0]': 1
  '[13, 12]': 1
  '[13, 14]': -1
  '[13, 2]': 1
  '[13, 3]': 1
  '[13, 6]': -1
  '[13, 7]': -1
  '[14, 11]': 1
  '[14, 13]': 1
  '[14, 15]': 1
  '[14, 16]': 1
  '[14, 2]': -1
  '[14, 8]': -1
  '[15, 13]': 1
  '[15, 14]': 1
  '[15, 16]': 1
  '[15, 1]': 1
  '[15, 2]': 1
  '[15, 6]': -1
  '[16, 0]': -1
  '[16, 11]': -1
  '[16, 13]': 1
  '[16, 15]': 1
  '[16, 16]': -1
  '[16, 1]': -1
  '[16, 4]': 1
  '[16, 5]': -1
  '[16, 6]': -1
  '[16, 8]': 1
  '[2, 0]': 1
  '[2, 13]': 1
  '[2, 15]': 1
  '[2, 1]': 1
  '[2, 2]': -1
  '[3, 12]': -1
  '[3, 14]': -1
  '[3, 2]': -1
  '[3, 4]': 1
  '[4, 10]': -1
  '[4, 12]': 1
  '[4, 3]': -1
  '[4, 4]': 1
  '[4, 7]': 1
  '[4, 8]': 1
  '[5, 0]': -1
  '[5, 13]': 1
  '[5, 3]': 1
  '[5, 4]': 1
  '[5, 6]': -1
  '[5, 8]': 1
  '[5, 9]': -1
  '[6, 11]': -1
  '[6, 14]': 1
  '[6, 16]': -1
  '[6, 2]': 1
  '[7, 15]': -1
  '[7, 16]': 1
  '[7, 7]': 1
  '[7, 8]': -1
  '[8, 15]': 1
  '[8, 8]': -1
  '[9, 0]': 1
  '[9, 11]': 1
  '[9, 12]': -1
  '[9, 1]': 1
  '[9, 6]': 1
size:
- 17
- 17
terminal_states: []
transition_prob: 0.8
walls:
- - 15
  - 16
- - 8
  - 6
- - 15
  - 8
- - 0
  - 7
- - 14
  - 3
- - 10
  - 16
- - 16
  - 11
- - 1
  - 9
- - 0
  - 13
- - 11
  - 0
- - 7
  - 6
- - 8
  - 8
- - 12
  - 0
- - 8
  - 0
- - 6
  - 11
- - 5
  - 7
white_reward: -0.04
