discount: 0.99
rewards:
  '[0, 3]': -1
  '[0, 5]': 1
  '[0, 6]': 1
  '[1, 6]': -1
  '[1, 8]': -1
  '[3, 5]': -1
  '[4, 1]': -1
  '[4, 4]': 1
  '[4, 5]': 1
  '[5, 0]': 1
  '[5, 2]': -1
  '[5, 3]': -1
  '[5, 6]': -1
  '[5, 7]': 1
  '[5, 8]': 1
  '[6, 0]': 1
  '[6, 4]': -1
  '[6, 8]': 1
  '[7, 0]': -1
  '[7, 4]': -1
  '[8, 0]': -1
  '[8, 1]': 1
  '[8, 3]': 1
  '[8, 4]': 1
  '[8, 5]': 1
  '[8, 7]': 1
  '[8, 8]': 1
size:
- 9
- 9
terminal_states: []
transition_prob: 0.8
walls:
- - 6
  - 4
- - 2
  - 8
- - 8
  - 7
- - 6
  - 0
- - 2
  - 2
- - 3
  - 1
- - 0
  - 0
- - 3
  - 0
white_reward: -0.04
