discount: 0.99
rewards:
  '[0, 10]': -1
  '[0, 1]': 1
  '[0, 2]': -1
  '[0, 4]': -1
  '[0, 8]': 1
  '[1, 2]': -1
  '[1, 3]': 1
  '[1, 4]': 1
  '[1, 8]': -1
  '[10, 10]': -1
  '[10, 3]': 1
  '[10, 5]': -1
  '[2, 10]': -1
  '[2, 1]': -1
  '[2, 3]': -1
  '[3, 1]': 1
  '[3, 2]': -1
  '[3, 3]': 1
  '[3, 4]': -1
  '[3, 7]': 1
  '[3, 8]': 1
  '[4, 10]': -1
  '[4, 1]': 1
  '[4, 3]': 1
  '[5, 3]': 1
  '[5, 5]': 1
  '[6, 1]': 1
  '[6, 9]': -1
  '[7, 10]': -1
  '[7, 3]': 1
  '[7, 4]': 1
  '[7, 6]': -1
  '[7, 7]': -1
  '[8, 5]': 1
  '[8, 8]': -1
  '[9, 2]': -1
  '[9, 5]': -1
  '[9, 6]': -1
  '[9, 7]': 1
  '[9, 8]': 1
size:
- 11
- 11
terminal_states: []
transition_prob: 0.8
walls:
- - 6
  - 4
- - 8
  - 10
- - 0
  - 9
- - 8
  - 6
- - 7
  - 3
- - 1
  - 1
- - 6
  - 5
- - 7
  - 1
- - 5
  - 10
- - 7
  - 4
white_reward: -0.04
