discount: 0.99
rewards:
  '[0, 5]': 1
  '[1, 0]': -1
  '[1, 1]': -1
  '[1, 2]': -1
  '[1, 3]': -1
  '[1, 4]': -1
  '[1, 6]': 1
  '[2, 0]': -1
  '[2, 1]': -1
  '[2, 6]': -1
  '[3, 0]': 1
  '[3, 4]': 1
  '[3, 6]': -1
  '[4, 3]': 1
  '[4, 6]': -1
  '[6, 6]': 1
size:
- 7
- 7
terminal_states: []
transition_prob: 0.8
walls:
- - 4
  - 1
- - 2
  - 1
- - 0
  - 6
- - 6
  - 2
- - 4
  - 4
- - 6
  - 6
white_reward: -0.04
